### PR TITLE
fix pca duty cycle values

### PR DESCRIPTION
**Pull request by RyAndrew**
pwm duty cycle value is 0-1

### CODE REVIEW

**Comment by ServeurpersoCom** [comment]
You can use PWMMIN and PWMMAX configuration;
But there is a / 100 missing for the function setDutyCycle(chPwm, pwm); that waiting for 0-1 float value

**Comment by ServeurpersoCom** [comment]
``` 
if(value < 0) {
  pca9685Driver[pcaId].channelOff(chIn1);
  pca9685Driver[pcaId].channelOn(chIn2);
  pwm = -value / 100;
 } else if(value > 0) {
  pca9685Driver[pcaId].channelOn(chIn1);
  pca9685Driver[pcaId].channelOff(chIn2);
  pwm = value / 100;
 } else {
  pca9685Driver[pcaId].channelOff(chIn1);
  pca9685Driver[pcaId].channelOff(chIn2);
  pwm = 0;
 }
```

**Comment by RyAndrew** [comment]
Yes that is best

**Comment by ServeurpersoCom** [comment]
We speaked with Mike and we think to put hardcoded MIN/MAX for board because easier for users and front-end/future GUI....

**Comment by RyAndrew** [comment]
Oui oui!
I agree motors control via PWM DutyCycle should be hardcoded Min and Max at -100 and 100.
Forward NEUTR and Reverse NEUTR should be the only 2 configs available.

**Comment by ServeurpersoCom** [comment]
I pushed this.
Need tests for I2C (and also PWM) :)

**Pull request closed without merging**
